name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Node v10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      with:
        version: 2018.11.26
    - name: Install python dependencies
      run: |
        python --version
        pipenv --version
        pipenv lock --requirements > requirements.txt
        cat requirements.txt
        pip install -r requirements.txt
        pytest --version
    - name: Install node dependencies
      run: |
        pwd
        node --version
        cd client/
        yarn install
        yarn build
    - name: Run python tests
      run: |
        pwd
        pytest
