name: Python application
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install Yarn 1.x
      run: npm install -g yarn@1.22.22
    - name: Install python dependencies
      run: |
        python --version
        pip install -r requirements.txt
    - name: Install node dependencies and build frontend
      run: |
        node --version
        yarn --version
        cd client/
        yarn install
        yarn build
    - name: Run python tests
      run: |
        pytest
