name: Python application
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install python dependencies
      run: |
        python --version
        pip install -r requirements.txt
    - name: Remove conflicting package-lock.json
      run: |
        cd client/
        rm -f package-lock.json
    - name: Install node dependencies & build index file
      run: |
        node --version
        cd client/
        yarn install
        CI=false yarn build
    - name: Run python tests
      run: |
        pytest
